<a href="https://colab.research.google.com/github/arzuantor/Spam-Email-Detection/blob/main/Spam_Email_Detection_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import Libraries

In [15]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import re
from sklearn.feature_extraction.text import TfidfVectorizer

#Load Dataset

In [2]:
df=pd.read_csv('spam.csv')

#See First 5 Data

In [9]:
df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

#Text-to-Numeric Label Encoding

In [6]:
le=LabelEncoder()

In [7]:
df['Category']=le.fit_transform(df['Category'])

In [8]:
df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

#Text Cleaning

In [13]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text
df['Message']=df['Message'].apply(clean_text)

In [14]:
df.head()

   Category                                            Message
0         0  go until jurong point crazy available only in ...
1         0                            ok lar joking wif u oni
2         1  free entry in  a wkly comp to win fa cup final...
3         0        u dun say so early hor u c already then say
4         0  nah i dont think he goes to usf he lives aroun...

#Subject Creating

In [21]:
vec=TfidfVectorizer()

# use vectorizer for the data

In [23]:
x=vec.fit_transform(df['Message'])
y=df['Category']

#check the data shape

In [25]:
print(X.shape)

(5572, 8605)