<a href="https://colab.research.google.com/github/arzuantor/Spam-Email-Detection/blob/main/Spam_Email_Detection_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import Libraries

In [43]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

#Load Dataset

In [2]:
df=pd.read_csv('spam.csv')

#See First 5 Data

In [9]:
df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

#Text-to-Numeric Label Encoding

In [6]:
le=LabelEncoder()

In [7]:
df['Category']=le.fit_transform(df['Category'])

In [8]:
df.head()

   Category                                            Message
0         0  Go until jurong point, crazy.. Available only ...
1         0                      Ok lar... Joking wif u oni...
2         1  Free entry in 2 a wkly comp to win FA Cup fina...
3         0  U dun say so early hor... U c already then say...
4         0  Nah I don't think he goes to usf, he lives aro...

#Text Cleaning

In [13]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-zA-Z ]', '', text)
    return text
df['Message']=df['Message'].apply(clean_text)

In [14]:
df.head()

   Category                                            Message
0         0  go until jurong point crazy available only in ...
1         0                            ok lar joking wif u oni
2         1  free entry in  a wkly comp to win fa cup final...
3         0        u dun say so early hor u c already then say
4         0  nah i dont think he goes to usf he lives aroun...

#Subject Creating

In [21]:
vec=TfidfVectorizer()

# use vectorizer for the data

In [23]:
x=vec.fit_transform(df['Message'])
y=df['Category']

#check the data shape

In [25]:
print(X.shape)

(5572, 8605)

#use train test split

In [29]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=.2,random_state=42)

#create logistic regression subject

In [35]:
model=LogisticRegression()

#fit the model

In [37]:
model.fit(xtrain, ytrain)

LogisticRegression()

#predict the model

In [41]:
ypred = model.predict(xtest)

#Model Evaluation

Check the accuracy

In [45]:
accuracy = accuracy_score(ytest, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.9605381165919282

Use confusion matrix

In [47]:
print(confusion_matrix(ytest, y_pred))

[[965   1]
 [ 43 106]]

check Classification report

In [49]:
print(classification_report(ytest, y_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       966
           1       0.99      0.71      0.83       149

    accuracy                           0.96      1115
   macro avg       0.97      0.86      0.90      1115
weighted avg       0.96      0.96      0.96      1115

#Real Message Test (demo)

In [51]:
msg = ["Free lottery winner claim now"]
print(model.predict(vec.transform(msg)))

[1]

In [59]:
msg = ["urgent you have won a week free membership"]

pred = model.predict(vec.transform(msg))

if pred[0] == 1:
    print("Spam")
else:
    print("Not Spam")

Spam